(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var c="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},d;if("function"==typeof Object.setPrototypeOf)d=Object.setPrototypeOf;else{var f;a:{var g={a:!0},h={};try{h.__proto__=g;f=h.a;break a}catch(a){}f=!1}d=f?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var k=d,l=this||self;function n(a,b){var e=String(b).toLowerCase();a=String(a.substr(0,b.length)).toLowerCase();return 0==(e<a?-1:e==a?0:1)};function p(a,b){this.g=b===q?a:""}p.prototype.i=!0;p.prototype.h=function(){return this.g.toString()};p.prototype.toString=function(){return this.g.toString()};function r(a){var b=a.indexOf("#");0<b&&(a=a.substring(0,b));b=a.match(/[?&]body=/gi);if(!b)return!0;if(1<b.length)return!1;a=a.match(/[?&]body=([^&]*)/)[1];if(!a)return!0;try{decodeURIComponent(a)}catch(e){return!1}return/^(?:[a-z0-9\-_.~]|%[0-9a-f]{2})+$/i.test(a)}var t=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,q={};function u(){var a=HTMLElement.call(this)||this;a.h=a.dial.bind(a);a.i=!1;return a}var v=HTMLElement;u.prototype=c(v.prototype);u.prototype.constructor=u;if(k)k(u,v);else for(var w in v)if("prototype"!=w)if(Object.defineProperties){var x=Object.getOwnPropertyDescriptor(v,w);x&&Object.defineProperty(u,w,x)}else u[w]=v[w];
u.prototype.connectedCallback=function(){if(!this.i){for(this.g=this.ownerDocument.createElement("gwd-taparea");this.children.length;)this.g.appendChild(this.firstChild);this.appendChild(this.g);this.i=!0}this.g.addEventListener("action",this.h)};u.prototype.disconnectedCallback=function(){this.g.removeEventListener("action",this.h,!1)};
u.prototype.dial=function(){var a=this.getAttribute("number")||"",b=decodeURI(a)!==decodeURIComponent(a)?a:encodeURIComponent(a);a=this.hasAttribute("action")&&"sms"===this.getAttribute("action").toLowerCase()?"sms":"tel";b=a+":"+b;var e={url:b};e=void 0===e?null:e;var m=document.createEvent("CustomEvent");m.initCustomEvent("taptocall",!0,!0,e);this.dispatchEvent(m);m.detail.handled||("tel"===a?(a=b,n(a,"tel:")||(a="about:invalid#zClosurez"),a=new p(a,q)):(a=b,n(a,"sms:")&&r(a)||(a="about:invalid#zClosurez"),
a=new p(a,q)),a instanceof p||a instanceof p||(a="object"==typeof a&&a.i?a.h():String(a),t.test(a)||(a="about:invalid#zClosurez"),a=new p(a,q)),l.open(a instanceof p&&a.constructor===p?a.g:"type_error:SafeUrl",""))};customElements.define("gwd-taptocall",u);}).call(this);
